/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.julio.vistas;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.julio.controladores.C_Conexion;
import com.julio.utils.guiStyles;

/**
 *
 * @author ACER
 */
public class frm_menu extends javax.swing.JFrame {

    /**
     * Creates new form frm_menu
     */
    public frm_menu() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp_menu = new javax.swing.JDesktopPane();
        mb_menu = new javax.swing.JMenuBar();
        m_calzado = new javax.swing.JMenu();
        mi_agregarCalzado = new javax.swing.JMenuItem();
        mi_buscarCalzado = new javax.swing.JMenuItem();
        mi_modificarCalzado = new javax.swing.JMenuItem();
        mi_reporteCalzado = new javax.swing.JMenuItem();
        m_venta = new javax.swing.JMenu();
        mi_registrarVenta = new javax.swing.JMenuItem();
        mi_reporteVenta = new javax.swing.JMenuItem();
        m_separado = new javax.swing.JMenu();
        mi_registrarSeparado = new javax.swing.JMenuItem();
        mi_reporteSeparado = new javax.swing.JMenuItem();
        m_cliente = new javax.swing.JMenu();
        mi_agregarCliente = new javax.swing.JMenuItem();
        mi_buscarCliente = new javax.swing.JMenuItem();
        mi_modificarCliente = new javax.swing.JMenuItem();
        mi_reporteCliente = new javax.swing.JMenuItem();
        m_facturacion = new javax.swing.JMenu();
        mi_agregarFactura = new javax.swing.JMenuItem();
        mi_buscarFactura = new javax.swing.JMenuItem();
        m_ayuda = new javax.swing.JMenu();
        mi_ayuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 720));

        dp_menu.setBackground(new java.awt.Color(252, 255, 255));

        javax.swing.GroupLayout dp_menuLayout = new javax.swing.GroupLayout(dp_menu);
        dp_menu.setLayout(dp_menuLayout);
        dp_menuLayout.setHorizontalGroup(
            dp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );
        dp_menuLayout.setVerticalGroup(
            dp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        m_calzado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/zapato-dama-58.png"))); // NOI18N
        m_calzado.setText("Calzado");

        mi_agregarCalzado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir-24.png"))); // NOI18N
        mi_agregarCalzado.setText("Agregar");
        mi_agregarCalzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_agregarCalzadoActionPerformed(evt);
            }
        });
        m_calzado.add(mi_agregarCalzado);

        mi_buscarCalzado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/búsqueda-24.png"))); // NOI18N
        mi_buscarCalzado.setText("Buscar");
        mi_buscarCalzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_buscarCalzadoActionPerformed(evt);
            }
        });
        m_calzado.add(mi_buscarCalzado);

        mi_modificarCalzado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/modificar-24.png"))); // NOI18N
        mi_modificarCalzado.setText("Modificar");
        mi_modificarCalzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_modificarCalzadoActionPerformed(evt);
            }
        });
        m_calzado.add(mi_modificarCalzado);

        mi_reporteCalzado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/report-24.png"))); // NOI18N
        mi_reporteCalzado.setText("Reporte de calzados");
        mi_reporteCalzado.setToolTipText("");
        mi_reporteCalzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_reporteCalzadoActionPerformed(evt);
            }
        });
        m_calzado.add(mi_reporteCalzado);

        mb_menu.add(m_calzado);

        m_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/bolsa-de-papel-58.png"))); // NOI18N
        m_venta.setText("Venta");

        mi_registrarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sales-24.png"))); // NOI18N
        mi_registrarVenta.setText("Registrar");
        mi_registrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_registrarVentaActionPerformed(evt);
            }
        });
        m_venta.add(mi_registrarVenta);

        mi_reporteVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/report-24.png"))); // NOI18N
        mi_reporteVenta.setText("Reporte de ventas");
        mi_reporteVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_reporteVentaActionPerformed(evt);
            }
        });
        m_venta.add(mi_reporteVenta);

        mb_menu.add(m_venta);

        m_separado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pin-60.png"))); // NOI18N
        m_separado.setText("Separar");

        mi_registrarSeparado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sales-24.png"))); // NOI18N
        mi_registrarSeparado.setText("Registrar");
        mi_registrarSeparado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_registrarSeparadoActionPerformed(evt);
            }
        });
        m_separado.add(mi_registrarSeparado);

        mi_reporteSeparado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/report-24.png"))); // NOI18N
        mi_reporteSeparado.setText("Reporte de separados");
        mi_reporteSeparado.setToolTipText("");
        mi_reporteSeparado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_reporteSeparadoActionPerformed(evt);
            }
        });
        m_separado.add(mi_reporteSeparado);

        mb_menu.add(m_separado);

        m_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mujer-48.png"))); // NOI18N
        m_cliente.setText("Cliente");

        mi_agregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir-24.png"))); // NOI18N
        mi_agregarCliente.setText("Agregar");
        mi_agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_agregarClienteActionPerformed(evt);
            }
        });
        m_cliente.add(mi_agregarCliente);

        mi_buscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/búsqueda-24.png"))); // NOI18N
        mi_buscarCliente.setText("Buscar");
        mi_buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_buscarClienteActionPerformed(evt);
            }
        });
        m_cliente.add(mi_buscarCliente);

        mi_modificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/modificar-24.png"))); // NOI18N
        mi_modificarCliente.setText("Modificar");
        mi_modificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_modificarClienteActionPerformed(evt);
            }
        });
        m_cliente.add(mi_modificarCliente);

        mi_reporteCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/report-24.png"))); // NOI18N
        mi_reporteCliente.setText("Reporte de clientes");
        mi_reporteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_reporteClienteActionPerformed(evt);
            }
        });
        m_cliente.add(mi_reporteCliente);

        mb_menu.add(m_cliente);

        m_facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/factura-58.png"))); // NOI18N
        m_facturacion.setText("Facturacion");

        mi_agregarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir-24.png"))); // NOI18N
        mi_agregarFactura.setText("Agregar");
        mi_agregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_agregarFacturaActionPerformed(evt);
            }
        });
        m_facturacion.add(mi_agregarFactura);

        mi_buscarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/búsqueda-24.png"))); // NOI18N
        mi_buscarFactura.setText("Buscar");
        mi_buscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_buscarFacturaActionPerformed(evt);
            }
        });
        m_facturacion.add(mi_buscarFactura);

        mb_menu.add(m_facturacion);

        m_ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/help-58.png"))); // NOI18N
        m_ayuda.setText("Ayuda");

        mi_ayuda.setText("Acerca de");
        mi_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ayudaActionPerformed(evt);
            }
        });
        m_ayuda.add(mi_ayuda);

        mb_menu.add(m_ayuda);

        setJMenuBar(mb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_menu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_menu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_agregarCalzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_agregarCalzadoActionPerformed
        ifrm_agregarCalzado agregar = new ifrm_agregarCalzado();
        guiStyles.centrarInternalVentana(dp_menu, agregar);
    }//GEN-LAST:event_mi_agregarCalzadoActionPerformed

    private void mi_buscarCalzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_buscarCalzadoActionPerformed
        ifrm_buscarCalzado buscar = new ifrm_buscarCalzado();
        guiStyles.centrarInternalVentana(dp_menu, buscar);
    }//GEN-LAST:event_mi_buscarCalzadoActionPerformed

    private void mi_modificarCalzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_modificarCalzadoActionPerformed
        ifrm_modificarCalzado modificar = new ifrm_modificarCalzado();
        guiStyles.centrarInternalVentana(dp_menu, modificar);
    }//GEN-LAST:event_mi_modificarCalzadoActionPerformed

    private void mi_reporteCalzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_reporteCalzadoActionPerformed
        ifrm_reporteCalzado reporte = new ifrm_reporteCalzado();
        guiStyles.centrarInternalVentana(dp_menu, reporte);
    }//GEN-LAST:event_mi_reporteCalzadoActionPerformed

    private void mi_registrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_registrarVentaActionPerformed
        ifrm_registrarVenta registrarVenta = new ifrm_registrarVenta();
        guiStyles.centrarInternalVentana(dp_menu, registrarVenta);
    }//GEN-LAST:event_mi_registrarVentaActionPerformed

    private void mi_reporteVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_reporteVentaActionPerformed
        ifrm_reporteVenta reporteVenta = new ifrm_reporteVenta();
        guiStyles.centrarInternalVentana(dp_menu, reporteVenta);
    }//GEN-LAST:event_mi_reporteVentaActionPerformed

    private void mi_registrarSeparadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_registrarSeparadoActionPerformed
        ifrm_registrarSeparado separado = new ifrm_registrarSeparado();
        guiStyles.centrarInternalVentana(dp_menu, separado);
    }//GEN-LAST:event_mi_registrarSeparadoActionPerformed

    private void mi_reporteSeparadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_reporteSeparadoActionPerformed
        ifrm_reporteSeparado reporteSeparado = new ifrm_reporteSeparado();
        guiStyles.centrarInternalVentana(dp_menu, reporteSeparado);
    }//GEN-LAST:event_mi_reporteSeparadoActionPerformed

    private void mi_agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_agregarClienteActionPerformed
        ifrm_agregarCliente cliente = new ifrm_agregarCliente();
        guiStyles.centrarInternalVentana(dp_menu, cliente);
    }//GEN-LAST:event_mi_agregarClienteActionPerformed

    private void mi_buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_buscarClienteActionPerformed
        ifrm_buscarCliente cliente = new ifrm_buscarCliente();
        guiStyles.centrarInternalVentana(dp_menu, cliente);
    }//GEN-LAST:event_mi_buscarClienteActionPerformed

    private void mi_modificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_modificarClienteActionPerformed
        ifrm_modificarCliente modificar = new ifrm_modificarCliente();
        guiStyles.centrarInternalVentana(dp_menu, modificar);
    }//GEN-LAST:event_mi_modificarClienteActionPerformed

    private void mi_reporteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_reporteClienteActionPerformed
        ifrm_reporteCliente reporteCliente = new ifrm_reporteCliente();
        guiStyles.centrarInternalVentana(dp_menu, reporteCliente);
    }//GEN-LAST:event_mi_reporteClienteActionPerformed

    private void mi_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ayudaActionPerformed
        ifrm_acercaAyuda ayuda = new ifrm_acercaAyuda();
        guiStyles.centrarInternalVentana(dp_menu, ayuda);
    }//GEN-LAST:event_mi_ayudaActionPerformed

    private void mi_agregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_agregarFacturaActionPerformed
        ifrm_agregarFactura agregarFactura = new ifrm_agregarFactura();
        guiStyles.centrarInternalVentana(dp_menu, agregarFactura);
        
    }//GEN-LAST:event_mi_agregarFacturaActionPerformed

    private void mi_buscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_buscarFacturaActionPerformed
        ifrm_buscarFactura buscarFactura = new ifrm_buscarFactura();
        guiStyles.centrarInternalVentana(dp_menu, buscarFactura);
    }//GEN-LAST:event_mi_buscarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dp_menu;
    private javax.swing.JMenu m_ayuda;
    private javax.swing.JMenu m_calzado;
    private javax.swing.JMenu m_cliente;
    private javax.swing.JMenu m_facturacion;
    private javax.swing.JMenu m_separado;
    private javax.swing.JMenu m_venta;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuItem mi_agregarCalzado;
    private javax.swing.JMenuItem mi_agregarCliente;
    private javax.swing.JMenuItem mi_agregarFactura;
    private javax.swing.JMenuItem mi_ayuda;
    private javax.swing.JMenuItem mi_buscarCalzado;
    private javax.swing.JMenuItem mi_buscarCliente;
    private javax.swing.JMenuItem mi_buscarFactura;
    private javax.swing.JMenuItem mi_modificarCalzado;
    private javax.swing.JMenuItem mi_modificarCliente;
    private javax.swing.JMenuItem mi_registrarSeparado;
    private javax.swing.JMenuItem mi_registrarVenta;
    private javax.swing.JMenuItem mi_reporteCalzado;
    private javax.swing.JMenuItem mi_reporteCliente;
    private javax.swing.JMenuItem mi_reporteSeparado;
    private javax.swing.JMenuItem mi_reporteVenta;
    // End of variables declaration//GEN-END:variables
}
