/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.julio.vistas;

import com.julio.controladores.C_cargarMarcas;
import com.julio.dao.DAODetalleFacturacionImple;
import com.julio.dao.DAOFacturacionImple;
import com.julio.interfaces.DAODetalleFacturacion;
import com.julio.interfaces.DAOFacturacion;
import com.julio.modelos.Calzado;
import com.julio.modelos.DetalleFacturacion;
import com.julio.modelos.Facturacion;
import com.julio.modelos.Marca;
import com.julio.utils.fontStyles;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class ifrm_agregarFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrm_agregarFactura
     */
    public ifrm_agregarFactura() {
        initComponents();
        initStyles();
        initContent();
    }

    private void initStyles() {
        fontStyles.estiloAgregarFactura(lbl_titulo, lbl_factura, lbl_fecha, lbl_barra, lbl_cantidad, lbl_marca);
    }

    private void initContent() {
        C_cargarMarcas cargarMarcas = new C_cargarMarcas(cb_marca);
        cargarMarcas.llenarComboMarca();
        JTextFieldDateEditor editor = (JTextFieldDateEditor) dc_fechaEmision.getDateEditor();
        editor.setEditable(false);
        dc_fechaEmision.setMaxSelectableDate(new Date());
        ((JSpinner.DefaultEditor) sp_cantidad.getEditor()).getTextField().setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_registrarSeparado = new javax.swing.JPanel();
        pnl_encabezado = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_contenido = new javax.swing.JPanel();
        lbl_factura = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_barra = new javax.swing.JLabel();
        lbl_marca = new javax.swing.JLabel();
        txt_barra = new javax.swing.JTextField();
        btn_buscarRef = new javax.swing.JButton();
        dc_fechaEmision = new com.toedter.calendar.JDateChooser();
        txt_factura = new javax.swing.JTextField();
        cb_marca = new javax.swing.JComboBox<>();
        btn_agregarTabla = new javax.swing.JButton();
        lbl_cantidad = new javax.swing.JLabel();
        sp_cantidad = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_detalleFactura = new javax.swing.JTable();
        pnl_pie = new javax.swing.JPanel();
        btn_guardar = new javax.swing.JButton();
        pnl_botonBorrar = new javax.swing.JPanel();
        btn_borrarSeleccion = new javax.swing.JButton();
        pnl_calzadoDesc = new javax.swing.JPanel();
        txt_calzadoDesc = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Registrar Factura");

        pnl_registrarSeparado.setBackground(new java.awt.Color(255, 255, 255));

        pnl_encabezado.setBackground(new java.awt.Color(0, 242, 242));
        pnl_encabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_titulo.setText("Ingrese los datos de la factura");

        javax.swing.GroupLayout pnl_encabezadoLayout = new javax.swing.GroupLayout(pnl_encabezado);
        pnl_encabezado.setLayout(pnl_encabezadoLayout);
        pnl_encabezadoLayout.setHorizontalGroup(
            pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_encabezadoLayout.setVerticalGroup(
            pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_encabezadoLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lbl_titulo)
                .addContainerGap())
        );

        pnl_contenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_factura.setText("Nro Factura");
        lbl_factura.setToolTipText("");

        lbl_fecha.setText("Fecha Emision");

        lbl_barra.setText("Codigo de Barras");

        lbl_marca.setText("Marca");

        txt_barra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_barra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_buscarRef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/busqueda-14.png"))); // NOI18N
        btn_buscarRef.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dc_fechaEmision.setBackground(new java.awt.Color(255, 255, 153));
        dc_fechaEmision.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dc_fechaEmision.setDateFormatString("yyyy-MM-dd");
        dc_fechaEmision.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txt_factura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_factura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cb_marca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_marca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_agregarTabla.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_agregarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir-30.png"))); // NOI18N
        btn_agregarTabla.setText("Agregar");
        btn_agregarTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_agregarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarTablaActionPerformed(evt);
            }
        });

        lbl_cantidad.setText("Cantidad");

        sp_cantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sp_cantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_contenidoLayout = new javax.swing.GroupLayout(pnl_contenido);
        pnl_contenido.setLayout(pnl_contenidoLayout);
        pnl_contenidoLayout.setHorizontalGroup(
            pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_agregarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_contenidoLayout.createSequentialGroup()
                        .addGroup(pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnl_contenidoLayout.createSequentialGroup()
                                .addComponent(lbl_cantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_contenidoLayout.createSequentialGroup()
                                .addComponent(lbl_marca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_contenidoLayout.createSequentialGroup()
                                .addGroup(pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_barra)
                                    .addComponent(lbl_fecha)
                                    .addComponent(lbl_factura))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_factura, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dc_fechaEmision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(txt_barra, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscarRef, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnl_contenidoLayout.setVerticalGroup(
            pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_factura)
                    .addComponent(txt_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_fecha)
                    .addComponent(dc_fechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscarRef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_barra)
                        .addComponent(txt_barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_marca, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cantidad))
                .addGap(119, 119, 119)
                .addComponent(btn_agregarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        tbl_detalleFactura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbl_detalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° FACTURA", "C_BARRA", "CANTIDAD"
            }
        ));
        jScrollPane1.setViewportView(tbl_detalleFactura);

        pnl_pie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/save-30.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_pieLayout = new javax.swing.GroupLayout(pnl_pie);
        pnl_pie.setLayout(pnl_pieLayout);
        pnl_pieLayout.setHorizontalGroup(
            pnl_pieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_pieLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_pieLayout.setVerticalGroup(
            pnl_pieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_pieLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_botonBorrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_borrarSeleccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_borrarSeleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar-30.png"))); // NOI18N
        btn_borrarSeleccion.setText("Borrar seleccion");
        btn_borrarSeleccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_borrarSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarSeleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_botonBorrarLayout = new javax.swing.GroupLayout(pnl_botonBorrar);
        pnl_botonBorrar.setLayout(pnl_botonBorrarLayout);
        pnl_botonBorrarLayout.setHorizontalGroup(
            pnl_botonBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_botonBorrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_borrarSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_botonBorrarLayout.setVerticalGroup(
            pnl_botonBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_botonBorrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_borrarSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_calzadoDesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_calzadoDesc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_calzadoDesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_calzadoDesc.setEnabled(false);

        javax.swing.GroupLayout pnl_calzadoDescLayout = new javax.swing.GroupLayout(pnl_calzadoDesc);
        pnl_calzadoDesc.setLayout(pnl_calzadoDescLayout);
        pnl_calzadoDescLayout.setHorizontalGroup(
            pnl_calzadoDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_calzadoDescLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_calzadoDesc)
                .addContainerGap())
        );
        pnl_calzadoDescLayout.setVerticalGroup(
            pnl_calzadoDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_calzadoDescLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txt_calzadoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_registrarSeparadoLayout = new javax.swing.GroupLayout(pnl_registrarSeparado);
        pnl_registrarSeparado.setLayout(pnl_registrarSeparadoLayout);
        pnl_registrarSeparadoLayout.setHorizontalGroup(
            pnl_registrarSeparadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registrarSeparadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_registrarSeparadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_registrarSeparadoLayout.createSequentialGroup()
                        .addComponent(pnl_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_registrarSeparadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_registrarSeparadoLayout.createSequentialGroup()
                                .addComponent(pnl_botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnl_pie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                            .addComponent(pnl_calzadoDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnl_registrarSeparadoLayout.setVerticalGroup(
            pnl_registrarSeparadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registrarSeparadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_registrarSeparadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_registrarSeparadoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(pnl_calzadoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(pnl_registrarSeparadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_pie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addComponent(pnl_contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_registrarSeparado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_registrarSeparado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarTablaActionPerformed
        if (!validarCampos()) {
            return;
        }
        agregarFilas();
        txt_factura.setEnabled(false);
        dc_fechaEmision.setEnabled(false);
        cb_marca.setEnabled(false);
        txt_barra.requestFocus();
    }//GEN-LAST:event_btn_agregarTablaActionPerformed

    private void agregarFilas() {
        String factura = txt_factura.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fecha_emision = sdf.format(dc_fechaEmision.getDate());
        String barra = txt_barra.getText();
        int cantidad = (Integer) sp_cantidad.getValue();
        //int marca_id = cb_marca.getItemAt(cb_marca.getSelectedIndex()).getId_marca();
        Object[] row = {factura, barra, cantidad, fecha_emision};
        DefaultTableModel dtm = (DefaultTableModel) tbl_detalleFactura.getModel();
        dtm.addRow(row);
    }

    private void btn_borrarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarSeleccionActionPerformed
        if (tbl_detalleFactura.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar 1 o mas filas", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int numRows = tbl_detalleFactura.getSelectedRows().length;
        DefaultTableModel dtm = (DefaultTableModel) tbl_detalleFactura.getModel();
        //De momento funciona piola este eliminador de filas
        for (int i = 0; i < numRows; i++) {
            dtm.removeRow(tbl_detalleFactura.getSelectedRow());
        }
        int rows = tbl_detalleFactura.getRowCount();
        if (rows == 0) {
            setFields(true);
        }
    }//GEN-LAST:event_btn_borrarSeleccionActionPerformed

    private void setFields(boolean flag) {
        txt_factura.setEnabled(flag);
        dc_fechaEmision.setEnabled(flag);
        cb_marca.setEnabled(flag);
    }
    
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        int numRow = tbl_detalleFactura.getRowCount();
        if (numRow == 0) {
            JOptionPane.showMessageDialog(null, "Debe agregar datos a la tabla, rellene los campos y clickee 'Agregar'", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        guardarFacturacion();
        guardarDetalleFacturacion();
    }//GEN-LAST:event_btn_guardarActionPerformed

    private boolean validarCampos() {
        if (txt_factura.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe insertar una factura", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txt_barra.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe insertar un codigo de barra", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        Date fecha = dc_fechaEmision.getDate();
        if (fecha == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fecha en la cajita de la derecha", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return true;
    }

    private void guardarFacturacion() {
        Date fecha_emision = dc_fechaEmision.getDate();
        long time = fecha_emision.getTime();
        java.sql.Date fecha_final = new java.sql.Date(time);
        //String factura = txt_factura.getText().trim().toUpperCase();
        String factura = (String) tbl_detalleFactura.getValueAt(0, 0);
        String factura_final = factura.trim().toUpperCase();
        int marca_id = cb_marca.getItemAt(cb_marca.getSelectedIndex()).getId_marca();

        Facturacion factos = new Facturacion();
        Marca marca = new Marca();
        factos.setNro_factura(factura_final);
        marca.setId_marca(marca_id);
        factos.setMarca(marca);
        factos.setFecha_emision(fecha_final);
        try {
            DAOFacturacion dao = new DAOFacturacionImple();
            dao.registrarFacturacion(factos);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo enviar a la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void guardarDetalleFacturacion() {
        List<DetalleFacturacion> detalles = obtenerDetallesTabla();
        try {
            DAODetalleFacturacion dao = new DAODetalleFacturacionImple();
            dao.registrarDetalleFacturacion(detalles);
            JOptionPane.showMessageDialog(null, "Factura y detalles guardados correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al registrar detalles: " + e.getMessage());
            e.printStackTrace();
        }

    }

    private List<DetalleFacturacion> obtenerDetallesTabla() {
        List<DetalleFacturacion> listaDetalles = new ArrayList<>();
        int rowCount = tbl_detalleFactura.getRowCount();
        for (int row = 0; row < rowCount; row++) {
            DetalleFacturacion d_facto = new DetalleFacturacion();
            Facturacion facturacion = new Facturacion();
            facturacion.setNro_factura((String) tbl_detalleFactura.getValueAt(row, 0));

            Calzado calzado = new Calzado();
            calzado.setCod_barra((String) tbl_detalleFactura.getValueAt(row, 1));

            d_facto.setFactura(facturacion);
            d_facto.setCalzado(calzado);
            d_facto.setCantidad((Integer) tbl_detalleFactura.getValueAt(0, 2));
            listaDetalles.add(d_facto);
        }
        return listaDetalles;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarTabla;
    private javax.swing.JButton btn_borrarSeleccion;
    private javax.swing.JButton btn_buscarRef;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<Marca> cb_marca;
    private com.toedter.calendar.JDateChooser dc_fechaEmision;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_barra;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_factura;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_botonBorrar;
    private javax.swing.JPanel pnl_calzadoDesc;
    private javax.swing.JPanel pnl_contenido;
    private javax.swing.JPanel pnl_encabezado;
    private javax.swing.JPanel pnl_pie;
    private javax.swing.JPanel pnl_registrarSeparado;
    private javax.swing.JSpinner sp_cantidad;
    private javax.swing.JTable tbl_detalleFactura;
    private javax.swing.JTextField txt_barra;
    private javax.swing.JTextField txt_calzadoDesc;
    private javax.swing.JTextField txt_factura;
    // End of variables declaration//GEN-END:variables
}
