/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.julio.vistas;

import com.julio.utils.fontStyles;

/**
 *
 * @author ACER
 */
public class ifrm_registrarVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrm_registrarVenta
     */
    public ifrm_registrarVenta() {
        initComponents();
        initStyles();
    }

    private void initStyles(){
        fontStyles.estiloRegistrarVenta(lbl_titulo, lbl_subtitulo, lbl_desc, lbl_dni,
                lbl_cantidad);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_registrarVenta = new javax.swing.JPanel();
        pnl_encabezado = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_imagen = new javax.swing.JLabel();
        lbl_subtitulo = new javax.swing.JLabel();
        lbl_desc = new javax.swing.JLabel();
        pnl_venta = new javax.swing.JPanel();
        lbl_barra = new javax.swing.JLabel();
        txt_barra = new javax.swing.JTextField();
        btn_buscarRef = new javax.swing.JButton();
        btn_buscarDni = new javax.swing.JButton();
        lbl_dni = new javax.swing.JLabel();
        txt_dni = new javax.swing.JTextField();
        lbl_cantidad = new javax.swing.JLabel();
        sp_cantidad = new javax.swing.JSpinner();
        pnl_barrera = new javax.swing.JPanel();
        txt_calzadoResul = new javax.swing.JTextField();
        txt_nombreResul = new javax.swing.JTextField();
        btn_agregarCarro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_carro = new javax.swing.JTable();
        btn_eliminarSeleccion = new javax.swing.JButton();
        txt_montoFinal = new javax.swing.JTextField();
        btn_eliminarSeleccion1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registrar Venta");

        pnl_registrarVenta.setBackground(new java.awt.Color(255, 255, 255));

        pnl_encabezado.setBackground(new java.awt.Color(252, 231, 244));
        pnl_encabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_titulo.setText("MIA SHOES");

        lbl_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mia_shoes_76.jpg"))); // NOI18N

        lbl_subtitulo.setText("VENTA DE CALZADO BRASILEÑO");

        lbl_desc.setText("Ingrese los datos de la venta");

        javax.swing.GroupLayout pnl_encabezadoLayout = new javax.swing.GroupLayout(pnl_encabezado);
        pnl_encabezado.setLayout(pnl_encabezadoLayout);
        pnl_encabezadoLayout.setHorizontalGroup(
            pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_imagen)
                .addGroup(pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addGroup(pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_subtitulo)
                            .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lbl_desc))))
                    .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(lbl_titulo)))
                .addContainerGap(378, Short.MAX_VALUE))
        );
        pnl_encabezadoLayout.setVerticalGroup(
            pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                        .addComponent(lbl_titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_subtitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_desc))
                    .addComponent(lbl_imagen))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pnl_venta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/código-de-barras-30.png"))); // NOI18N

        btn_buscarRef.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_buscarRef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/búsqueda-24.png"))); // NOI18N
        btn_buscarRef.setText(" ");

        btn_buscarDni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_buscarDni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/búsqueda-24.png"))); // NOI18N
        btn_buscarDni.setText(" ");

        lbl_dni.setText("DNI");

        lbl_cantidad.setText("Cantidad");

        sp_cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        pnl_barrera.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnl_barreraLayout = new javax.swing.GroupLayout(pnl_barrera);
        pnl_barrera.setLayout(pnl_barreraLayout);
        pnl_barreraLayout.setHorizontalGroup(
            pnl_barreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        pnl_barreraLayout.setVerticalGroup(
            pnl_barreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txt_calzadoResul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_calzadoResul.setEnabled(false);

        txt_nombreResul.setEnabled(false);

        btn_agregarCarro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_agregarCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir-30.png"))); // NOI18N
        btn_agregarCarro.setText("Agregar al carrito");
        btn_agregarCarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_ventaLayout = new javax.swing.GroupLayout(pnl_venta);
        pnl_venta.setLayout(pnl_ventaLayout);
        pnl_ventaLayout.setHorizontalGroup(
            pnl_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cantidad)
                    .addComponent(lbl_dni)
                    .addComponent(lbl_barra))
                .addGap(18, 18, 18)
                .addGroup(pnl_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_cantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscarRef, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(pnl_barrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_calzadoResul, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addComponent(txt_nombreResul)
                    .addGroup(pnl_ventaLayout.createSequentialGroup()
                        .addComponent(btn_agregarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_ventaLayout.setVerticalGroup(
            pnl_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ventaLayout.createSequentialGroup()
                        .addGroup(pnl_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnl_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_barra)
                                .addComponent(btn_buscarRef, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_dni)
                            .addComponent(txt_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_ventaLayout.createSequentialGroup()
                        .addComponent(txt_calzadoResul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nombreResul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnl_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ventaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnl_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_cantidad)
                            .addComponent(sp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_ventaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btn_agregarCarro)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addComponent(pnl_barrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbl_carro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "C_BARRAS", "REF", "CANTIDAD", "PRECIO", "DESCUENTO", "TOTAL"
            }
        ));
        tbl_carro.setShowGrid(false);
        tbl_carro.setShowHorizontalLines(true);
        tbl_carro.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tbl_carro);

        btn_eliminarSeleccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_eliminarSeleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar-30.png"))); // NOI18N
        btn_eliminarSeleccion.setText("Eliminar seleccion");
        btn_eliminarSeleccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_montoFinal.setBackground(new java.awt.Color(245, 240, 160));
        txt_montoFinal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_montoFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_montoFinal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        btn_eliminarSeleccion1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_eliminarSeleccion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/dinero-65.png"))); // NOI18N
        btn_eliminarSeleccion1.setText("COBRAR");
        btn_eliminarSeleccion1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_eliminarSeleccion1.setIconTextGap(20);

        javax.swing.GroupLayout pnl_registrarVentaLayout = new javax.swing.GroupLayout(pnl_registrarVenta);
        pnl_registrarVenta.setLayout(pnl_registrarVentaLayout);
        pnl_registrarVentaLayout.setHorizontalGroup(
            pnl_registrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registrarVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_registrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(pnl_registrarVentaLayout.createSequentialGroup()
                        .addComponent(btn_eliminarSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_eliminarSeleccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_montoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_registrarVentaLayout.setVerticalGroup(
            pnl_registrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registrarVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_registrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_eliminarSeleccion1)
                    .addComponent(txt_montoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminarSeleccion))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_registrarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_registrarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarCarro;
    private javax.swing.JButton btn_buscarDni;
    private javax.swing.JButton btn_buscarRef;
    private javax.swing.JButton btn_eliminarSeleccion;
    private javax.swing.JButton btn_eliminarSeleccion1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_barra;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_desc;
    private javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_imagen;
    private javax.swing.JLabel lbl_subtitulo;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_barrera;
    private javax.swing.JPanel pnl_encabezado;
    private javax.swing.JPanel pnl_registrarVenta;
    private javax.swing.JPanel pnl_venta;
    private javax.swing.JSpinner sp_cantidad;
    private javax.swing.JTable tbl_carro;
    private javax.swing.JTextField txt_barra;
    private javax.swing.JTextField txt_calzadoResul;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_montoFinal;
    private javax.swing.JTextField txt_nombreResul;
    // End of variables declaration//GEN-END:variables
}
