/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.julio.vistas;

import com.julio.dao.DAOCalzadoImple;
import com.julio.interfaces.DAOCalzado;
import com.julio.utils.fontStyles;
import com.julio.utils.guiStyles;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class ifrm_buscarCalzado extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrm_buscarCalzado
     */
    private ifrm_agregarFactura facturaFrame;

    public ifrm_buscarCalzado() {
        initComponents();
        initStyles();
        tbl_busqueda.setDefaultEditor(Object.class, null);
        btn_agregarFactura.setVisible(false);
        //tbl_busqueda.setEnabled(false);
    }

    public ifrm_buscarCalzado(ifrm_agregarFactura facturaFrame) {
        initComponents();
        initStyles();
        this.facturaFrame = facturaFrame;
        btn_agregarFactura.setVisible(true);
        this.setTitle("Buscar calzados para la factura");
    }

    private void initStyles() {
        fontStyles.estiloBuscarCalzado(lbl_titulo, lbl_buscar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_buscar = new javax.swing.JPanel();
        pnl_encabezado = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_buscarContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_busqueda = new javax.swing.JTable();
        lbl_buscar = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_agregarFactura = new javax.swing.JButton();

        setClosable(true);
        setTitle("Buscar Calzado");

        pnl_buscar.setBackground(new java.awt.Color(200, 255, 180));

        pnl_encabezado.setBackground(new java.awt.Color(225, 255, 210));
        pnl_encabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_titulo.setText("**Busqueda de Calzado**");

        javax.swing.GroupLayout pnl_encabezadoLayout = new javax.swing.GroupLayout(pnl_encabezado);
        pnl_encabezado.setLayout(pnl_encabezadoLayout);
        pnl_encabezadoLayout.setHorizontalGroup(
            pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(lbl_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_encabezadoLayout.setVerticalGroup(
            pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_encabezadoLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(lbl_titulo)
                .addGap(36, 36, 36))
        );

        pnl_buscarContent.setBackground(new java.awt.Color(255, 255, 255));
        pnl_buscarContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_busqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbl_busqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C_BARRA", "REF", "COLOR", "MATERIAL", "TALLA", "STOCK", "MARCA", "PRECIO"
            }
        ));
        tbl_busqueda.setShowGrid(true);
        tbl_busqueda.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_busqueda);

        lbl_buscar.setText("Ingrese la referencia");

        txt_buscar.setBackground(new java.awt.Color(200, 255, 180));
        txt_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/búsqueda-24.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_agregarFactura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_agregarFactura.setText("Agregar a factura");
        btn_agregarFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_agregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_buscarContentLayout = new javax.swing.GroupLayout(pnl_buscarContent);
        pnl_buscarContent.setLayout(pnl_buscarContentLayout);
        pnl_buscarContentLayout.setHorizontalGroup(
            pnl_buscarContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_buscarContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_buscarContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addGroup(pnl_buscarContentLayout.createSequentialGroup()
                        .addComponent(lbl_buscar)
                        .addGap(18, 18, 18)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnl_buscarContentLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(btn_agregarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_buscarContentLayout.setVerticalGroup(
            pnl_buscarContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_buscarContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_buscarContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_buscar)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_agregarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_buscarLayout = new javax.swing.GroupLayout(pnl_buscar);
        pnl_buscar.setLayout(pnl_buscarLayout);
        pnl_buscarLayout.setHorizontalGroup(
            pnl_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_buscarContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_buscarLayout.setVerticalGroup(
            pnl_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_buscarContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String ref = txt_buscar.getText().trim().toUpperCase();
        if (!validarCampos(ref)) {
            return;
        }
        llenarTablaRef(ref);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_agregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarFacturaActionPerformed
        if (tbl_busqueda.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar que calzados quiere agregar a la facturacion", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        List<String> barra_obtenida = seleccionarBarras();
        facturaFrame.agregarFilas(barra_obtenida);
        this.dispose();
    }//GEN-LAST:event_btn_agregarFacturaActionPerformed

    public List<String> seleccionarBarras() {
        int numRows = tbl_busqueda.getSelectedRows().length;
        List<String> barra = new ArrayList<>();
        for (int i = 0; i < numRows; i++) {
            barra.add((String) tbl_busqueda.getValueAt(i, 0));
        }
        return barra;
    }

    private void llenarTablaRef(String campo) {
        try {
            DAOCalzado dao = new DAOCalzadoImple();
            DefaultTableModel dtm = (DefaultTableModel) tbl_busqueda.getModel();
            dtm.setRowCount(0);
            dao.listarCalzado(campo).forEach((u) -> dtm.addRow(new Object[]{u.getCod_barra(), u.getReferencia(), u.getColor(),
                u.getMaterial(), u.getTalla(), u.getStock(), u.getMarca().getNombre_marca(), u.getPrecio_sugerido()}));
            if (tbl_busqueda.getRowCount() <= 0) {
                int reply = JOptionPane.showConfirmDialog(null, "No se encontro la referencia: " + campo + "\nDesea agregar este calzado?", "INFORMACION", JOptionPane.YES_NO_CANCEL_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    ifrm_agregarCalzado agregarCalzado = new ifrm_agregarCalzado();
                    guiStyles.centrarInternalVentana(frm_menu.dp_menu, agregarCalzado);
                } else {
                    txt_buscar.setText("");
                    txt_buscar.requestFocus();
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar la tabla con los datos", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private boolean validarCampos(String ref) {
        if (ref.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una referencia", "Error", JOptionPane.ERROR_MESSAGE);
            txt_buscar.requestFocus();
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agregarFactura;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_buscar;
    private javax.swing.JPanel pnl_buscarContent;
    private javax.swing.JPanel pnl_encabezado;
    private javax.swing.JTable tbl_busqueda;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
