/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.julio.vistas;

import com.julio.utils.fontStyles;

/**
 *
 * @author ACER
 */
public class ifrm_registrarVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrm_registrarVenta
     */
    public ifrm_registrarVenta() {
        initComponents();
        initStyles();
    }
    
    private void initStyles(){
        fontStyles.estiloRegistrarVenta(lbl_mia, lbl_sub, lbl_contenido, lbl_dni, lbl_cantidad, lbl_descuento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_registrarVenta = new javax.swing.JPanel();
        pnl_encabezado = new javax.swing.JPanel();
        lbl_imagen = new javax.swing.JLabel();
        lbl_mia = new javax.swing.JLabel();
        lbl_sub = new javax.swing.JLabel();
        lbl_contenido = new javax.swing.JLabel();
        pnl_datos = new javax.swing.JPanel();
        lbl_barra = new javax.swing.JLabel();
        lbl_dni = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        txt_dni = new javax.swing.JTextField();
        txt_barra = new javax.swing.JTextField();
        btn_buscarRef = new javax.swing.JButton();
        btn_buscarNombre = new javax.swing.JButton();
        sp_cantidad = new javax.swing.JSpinner();
        lbl_descuento = new javax.swing.JLabel();
        txt_descuento = new javax.swing.JTextField();
        pnl_botonAgregar = new javax.swing.JPanel();
        btn_agregarCarro = new javax.swing.JButton();
        pnl_tabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_carro = new javax.swing.JTable();
        pnl_datosLlenos = new javax.swing.JPanel();
        txt_calzadoDatos = new javax.swing.JTextField();
        txt_clienteDatos = new javax.swing.JTextField();
        pnl_botonEliminar = new javax.swing.JPanel();
        btn_eliminarSeleccion = new javax.swing.JButton();
        pnl_monto = new javax.swing.JPanel();
        txt_monto = new javax.swing.JTextField();
        pnl_botonCobrar = new javax.swing.JPanel();
        btn_cobrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registrar Venta");

        pnl_encabezado.setBackground(new java.awt.Color(255, 255, 242));
        pnl_encabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mia_shoes_76.jpg"))); // NOI18N

        lbl_mia.setText("MIA SHOES");

        lbl_sub.setText("Venta de Calzados Brasileños");

        lbl_contenido.setText("Punto de Venta");

        javax.swing.GroupLayout pnl_encabezadoLayout = new javax.swing.GroupLayout(pnl_encabezado);
        pnl_encabezado.setLayout(pnl_encabezadoLayout);
        pnl_encabezadoLayout.setHorizontalGroup(
            pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_imagen)
                .addGroup(pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(lbl_mia))
                    .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(lbl_sub))
                    .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(lbl_contenido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_encabezadoLayout.setVerticalGroup(
            pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                        .addComponent(lbl_mia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_sub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_contenido)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_datos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/código-de-barras-30.png"))); // NOI18N

        lbl_dni.setText("DNI");

        lbl_cantidad.setText("Cantidad");

        txt_dni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_dni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_barra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_barra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_buscarRef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/busqueda-14.png"))); // NOI18N
        btn_buscarRef.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_buscarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/busqueda-14.png"))); // NOI18N
        btn_buscarNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sp_cantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sp_cantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_descuento.setText("Descuento");

        txt_descuento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_descuento.setForeground(new java.awt.Color(199, 199, 205));
        txt_descuento.setText("Opcional");
        txt_descuento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnl_botonAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_agregarCarro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_agregarCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir-30.png"))); // NOI18N
        btn_agregarCarro.setText("Agregar al carrito");
        btn_agregarCarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_botonAgregarLayout = new javax.swing.GroupLayout(pnl_botonAgregar);
        pnl_botonAgregar.setLayout(pnl_botonAgregarLayout);
        pnl_botonAgregarLayout.setHorizontalGroup(
            pnl_botonAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_botonAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_agregarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_botonAgregarLayout.setVerticalGroup(
            pnl_botonAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_botonAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_agregarCarro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_datosLayout = new javax.swing.GroupLayout(pnl_datos);
        pnl_datos.setLayout(pnl_datosLayout);
        pnl_datosLayout.setHorizontalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_datosLayout.createSequentialGroup()
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cantidad)
                            .addComponent(lbl_dni)
                            .addComponent(lbl_barra)
                            .addComponent(lbl_descuento))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_dni, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(txt_barra)
                            .addComponent(sp_cantidad)
                            .addComponent(txt_descuento, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_buscarRef, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(btn_buscarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(pnl_botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pnl_datosLayout.setVerticalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_barra)
                    .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_buscarRef)))
                .addGap(18, 18, 18)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_dni)
                    .addComponent(txt_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarNombre, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cantidad)
                    .addComponent(sp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_descuento)
                    .addComponent(txt_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_carro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C_BARRA", "REF", "CANTIDAD", "PRECIO", "DESCUENTO", "MONTO"
            }
        ));
        tbl_carro.setShowHorizontalLines(true);
        tbl_carro.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tbl_carro);

        javax.swing.GroupLayout pnl_tablaLayout = new javax.swing.GroupLayout(pnl_tabla);
        pnl_tabla.setLayout(pnl_tablaLayout);
        pnl_tablaLayout.setHorizontalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_tablaLayout.setVerticalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_datosLlenos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_calzadoDatos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_calzadoDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_calzadoDatos.setEnabled(false);

        txt_clienteDatos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_clienteDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_clienteDatos.setEnabled(false);

        javax.swing.GroupLayout pnl_datosLlenosLayout = new javax.swing.GroupLayout(pnl_datosLlenos);
        pnl_datosLlenos.setLayout(pnl_datosLlenosLayout);
        pnl_datosLlenosLayout.setHorizontalGroup(
            pnl_datosLlenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datosLlenosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_datosLlenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_calzadoDatos)
                    .addComponent(txt_clienteDatos))
                .addContainerGap())
        );
        pnl_datosLlenosLayout.setVerticalGroup(
            pnl_datosLlenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datosLlenosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txt_calzadoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_clienteDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnl_botonEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_eliminarSeleccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_eliminarSeleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar-30.png"))); // NOI18N
        btn_eliminarSeleccion.setText("Eliminar Seleccion");
        btn_eliminarSeleccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_botonEliminarLayout = new javax.swing.GroupLayout(pnl_botonEliminar);
        pnl_botonEliminar.setLayout(pnl_botonEliminarLayout);
        pnl_botonEliminarLayout.setHorizontalGroup(
            pnl_botonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_botonEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_eliminarSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_botonEliminarLayout.setVerticalGroup(
            pnl_botonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_botonEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_eliminarSeleccion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_monto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_monto.setBackground(new java.awt.Color(245, 240, 160));
        txt_monto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_monto.setEnabled(false);

        javax.swing.GroupLayout pnl_montoLayout = new javax.swing.GroupLayout(pnl_monto);
        pnl_monto.setLayout(pnl_montoLayout);
        pnl_montoLayout.setHorizontalGroup(
            pnl_montoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_montoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_monto, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_montoLayout.setVerticalGroup(
            pnl_montoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_montoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_monto, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_botonCobrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_cobrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/dinero-65.png"))); // NOI18N
        btn_cobrar.setText("COBRAR");
        btn_cobrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_botonCobrarLayout = new javax.swing.GroupLayout(pnl_botonCobrar);
        pnl_botonCobrar.setLayout(pnl_botonCobrarLayout);
        pnl_botonCobrarLayout.setHorizontalGroup(
            pnl_botonCobrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_botonCobrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cobrar, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_botonCobrarLayout.setVerticalGroup(
            pnl_botonCobrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_botonCobrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cobrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_registrarVentaLayout = new javax.swing.GroupLayout(pnl_registrarVenta);
        pnl_registrarVenta.setLayout(pnl_registrarVentaLayout);
        pnl_registrarVentaLayout.setHorizontalGroup(
            pnl_registrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registrarVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_registrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_registrarVentaLayout.createSequentialGroup()
                        .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_registrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_datosLlenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnl_registrarVentaLayout.createSequentialGroup()
                                .addComponent(pnl_botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnl_botonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_registrarVentaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pnl_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnl_registrarVentaLayout.setVerticalGroup(
            pnl_registrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registrarVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_registrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_registrarVentaLayout.createSequentialGroup()
                        .addComponent(pnl_datosLlenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_registrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_botonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(pnl_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_registrarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_registrarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarCarro;
    private javax.swing.JButton btn_buscarNombre;
    private javax.swing.JButton btn_buscarRef;
    private javax.swing.JButton btn_cobrar;
    private javax.swing.JButton btn_eliminarSeleccion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_barra;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_contenido;
    private javax.swing.JLabel lbl_descuento;
    private javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_imagen;
    private javax.swing.JLabel lbl_mia;
    private javax.swing.JLabel lbl_sub;
    private javax.swing.JPanel pnl_botonAgregar;
    private javax.swing.JPanel pnl_botonCobrar;
    private javax.swing.JPanel pnl_botonEliminar;
    private javax.swing.JPanel pnl_datos;
    private javax.swing.JPanel pnl_datosLlenos;
    private javax.swing.JPanel pnl_encabezado;
    private javax.swing.JPanel pnl_monto;
    private javax.swing.JPanel pnl_registrarVenta;
    private javax.swing.JPanel pnl_tabla;
    private javax.swing.JSpinner sp_cantidad;
    private javax.swing.JTable tbl_carro;
    private javax.swing.JTextField txt_barra;
    private javax.swing.JTextField txt_calzadoDatos;
    private javax.swing.JTextField txt_clienteDatos;
    private javax.swing.JTextField txt_descuento;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_monto;
    // End of variables declaration//GEN-END:variables
}
