/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.julio.vistas;

import com.julio.utils.fontStyles;

/**
 *
 * @author ACER
 */
public class ifrm_acercaAyuda extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrm_acercaAyuda
     */
    public ifrm_acercaAyuda() {
        initComponents();
        initStyles();
    }
    
    private void initStyles(){
        fontStyles.estiloAyudaleft(lbl_info, lbl_sistema, lbl_version, lbl_developer, lbl_correo, lbl_soporte);
        fontStyles.estiloAyudaright(lbl_nombre, lbl_numVersion, lbl_devNombre, lbl_correoGmail, lbl_numero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_acerca = new javax.swing.JPanel();
        pnl_encabezado = new javax.swing.JPanel();
        lbl_info = new javax.swing.JLabel();
        lbl_sistema = new javax.swing.JLabel();
        lbl_version = new javax.swing.JLabel();
        lbl_developer = new javax.swing.JLabel();
        lbl_correo = new javax.swing.JLabel();
        lbl_soporte = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_numVersion = new javax.swing.JLabel();
        lbl_devNombre = new javax.swing.JLabel();
        lbl_correoGmail = new javax.swing.JLabel();
        lbl_numero = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Acerca de");

        pnl_acerca.setBackground(new java.awt.Color(255, 255, 255));

        pnl_encabezado.setBackground(new java.awt.Color(0, 242, 242));
        pnl_encabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_info.setText("INFORMACION");

        javax.swing.GroupLayout pnl_encabezadoLayout = new javax.swing.GroupLayout(pnl_encabezado);
        pnl_encabezado.setLayout(pnl_encabezadoLayout);
        pnl_encabezadoLayout.setHorizontalGroup(
            pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_info)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_encabezadoLayout.setVerticalGroup(
            pnl_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_encabezadoLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(lbl_info)
                .addContainerGap())
        );

        lbl_sistema.setText("Sistema:");

        lbl_version.setText("Version:");

        lbl_developer.setText("Developer:");

        lbl_correo.setText("Correo");

        lbl_soporte.setText("Soporte:");

        lbl_nombre.setText("MIA SHOES PUNTO DE VENTA");

        lbl_numVersion.setText("1.0");

        lbl_devNombre.setText("Julio Cesar Montalvan Pereyra");

        lbl_correoGmail.setText("julio030902@gmail.com");

        lbl_numero.setText("+51 922 187 472");

        javax.swing.GroupLayout pnl_acercaLayout = new javax.swing.GroupLayout(pnl_acerca);
        pnl_acerca.setLayout(pnl_acercaLayout);
        pnl_acercaLayout.setHorizontalGroup(
            pnl_acercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_acercaLayout.createSequentialGroup()
                .addGroup(pnl_acercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_acercaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_acercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_developer)
                            .addComponent(lbl_sistema)
                            .addComponent(lbl_version)
                            .addComponent(lbl_correo))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_acercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_numVersion)
                            .addComponent(lbl_nombre)
                            .addComponent(lbl_devNombre)
                            .addComponent(lbl_correoGmail)
                            .addComponent(lbl_numero))
                        .addGap(0, 285, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnl_acercaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_soporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_acercaLayout.setVerticalGroup(
            pnl_acercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_acercaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_acercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sistema)
                    .addComponent(lbl_nombre))
                .addGap(18, 18, 18)
                .addGroup(pnl_acercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_version)
                    .addComponent(lbl_numVersion))
                .addGap(18, 18, 18)
                .addGroup(pnl_acercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_developer)
                    .addComponent(lbl_devNombre))
                .addGap(18, 18, 18)
                .addGroup(pnl_acercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_correo)
                    .addComponent(lbl_correoGmail))
                .addGap(18, 18, 18)
                .addGroup(pnl_acercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_soporte)
                    .addComponent(lbl_numero))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_acerca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_acerca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_correoGmail;
    private javax.swing.JLabel lbl_devNombre;
    private javax.swing.JLabel lbl_developer;
    private javax.swing.JLabel lbl_info;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_numVersion;
    private javax.swing.JLabel lbl_numero;
    private javax.swing.JLabel lbl_sistema;
    private javax.swing.JLabel lbl_soporte;
    private javax.swing.JLabel lbl_version;
    private javax.swing.JPanel pnl_acerca;
    private javax.swing.JPanel pnl_encabezado;
    // End of variables declaration//GEN-END:variables
}
